use Techshop;
-- Write an SQL query to retrieve a list of all orders along with customer information (e.g., customer name) for each order
select * from orders;
select * from customers;
select orders.orderID , customers.customerId ,customers.firstname,orders.totalamount
from orders inner join customers
on orders.customerId=customers.customerId;

-- Write an SQL query to find the total revenue generated by each electronic gadget product. Include the product name and the total revenue.
select * from products;
select* from orderdetails;

select  products.productId,products.productname,sum(products.price * orderdetails.quantity) Totalamount
from products inner join orderdetails
on products.productId = orderdetails.productId
group by products.productId
order by products.productId;

-- Write an SQL query to list all customers who have made at least one purchase. Include their names and contact information.
select customerId ,count(*)
from orders
group by customerId
having count(*)>0;

-- Write an SQL query to find the most popular electronic gadget, which is the one with the highest total quantity ordered. Include the product name and the total quantity ordered.
select products.ProductName , orderdetails.quantity
from products inner join orderdetails
on products.ProductId = orderdetails.ProductID
where orderdetails.quantity = (select max(orderdetails.quantity) from orderdetails);




-- Write an SQL query to retrieve a list of electronic gadgets along with their corresponding categories.
select * from products;
alter table products
add Categories varchar(100); 
update products 
set categories = case 
    when productid = '141' then 'education'
    when productid = '142' then 'education'
    when productid = '143' then 'communication'
    when productid = '145' then 'food'
    when productid = '147' then 'entertainment'
    when productid = '148' then 'entertainment'
    when productid = '149' then 'education'
    when productid = '150' then 'communication'
    when productid = '151' then 'communication'
    when productid = '152' then 'entertainment'
    when productid = '153' then 'storage'
    else NULL 
end
where productid in ('141', '142', '143', '145', '147', '148', '149', '150', '151', '152', '153');


INSERT INTO products(productid,Categories) VALUES
('141','smart'), ('142','smart'), ('143','sound'), ('145','food'), ('147','smart'),
('148','digital'), ('149','smart'), ('150','smart'), ('151','sound'), ('152','digital'),
('153','storage');

-- Write an SQL query to calculate the average order value for each customer. Include the customer's name and their average order value
select customers.firstname,customers.lastname,avg(totalamount)
from customers inner join orders
on customers.customerid = orders.customerId
group by customers.customerId;




-- Write an SQL query to find the order with the highest total revenue. Include the order ID, customer information, and the total revenue.
SELECT orders.OrderID,customers.FirstName,customers.LastName,orders.totalAmount AS TotalRevenue
FROM Orders JOIN Customers 
ON orders.CustomerID = customers.CustomerID
WHERE orders.totalAmount = (SELECT MAX(totalAmount) FROM Orders);


-- Write an SQL query to list electronic gadgets and the number of times each product has been ordered.
Select productId , count(*)
from orderdetails
group by productId;

select distinct c.CustomerId, c.FirstName, c.LastName
from Customers c
inner join Orders o on c.CustomerId = o.CustomerId
inner join  OrderDetails od on o.OrderId = od.OrderId
inner join Products p on od.ProductID = p.ProductID
where p.ProductName = 'Laptop';


-- Write an SQL query to calculate the total revenue generated by all orders placed within a specific time period. Allow users to input the start and end dates as parameters.
select sum(totalamount) from orders
where orderdate between '2024-04-20' and '2024-04-23';
